<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('industrial_estates', function (Blueprint $table) {
            $table->id();
            $table->string('industrial_estate_name', 150)->unique();

            $table->decimal('land_rent', 12, 2)->nullable();
            $table->string('land_rent_unit')->nullable();

            $table->decimal('land_premium', 15, 2)->nullable();
            $table->string('land_premium_unit')->nullable();

            $table->decimal('shed_rent', 10, 2)->nullable();
            $table->string('shed_rent_unit')->nullable();

            $table->decimal('shed_premium', 10, 2)->nullable();
            $table->string('shed_premium_unit')->nullable();

            $table->decimal('available_land', 10, 2)->nullable();
            $table->string('available_land_unit')->nullable();

            $table->decimal('available_shed', 12, 2)->nullable();
            $table->string('available_shed_unit')->nullable();

            $table->enum('availability', ['yes', 'no']);

            $table->timestamps();
        });

        DB::table('industrial_estates')->insert([
            [
                'industrial_estate_name' => 'A.D Nagar Industrial Estate',
                'land_rent' => '20000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '2000000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '5.00',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '-0.156',
                'available_land_unit' => 'Acre',
                'available_shed' => '1600.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Badharghat Industrial Estate',
                'land_rent' => '20000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '2000000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '5.00',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '0.034',
                'available_land_unit' => 'Acre',
                'available_shed' => '0.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Bodhjungnagar Industrial Area',
                'land_rent' => '10000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '1000000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '3.20',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '12.030',
                'available_land_unit' => 'Acre',
                'available_shed' => '0.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Dhajanagar Industrial Estate',
                'land_rent' => '6500.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '650000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '2.80',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '0.490',
                'available_land_unit' => 'Acre',
                'available_shed' => '2500.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Dharmanagar Industrial Estate',
                'land_rent' => '6500.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '650000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '2.80',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '4.180',
                'available_land_unit' => 'Acre',
                'available_shed' => '10000.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Dukli Industrial Area',
                'land_rent' => '8000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '700000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '4.40',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '15.148',
                'available_land_unit' => 'Acre',
                'available_shed' => '0.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'IIDC at Jalefa (SEZ)',
                'land_rent' => '8000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '1000000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '3.20',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '400.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '0.000',
                'available_land_unit' => 'Acre',
                'available_shed' => '0.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'no',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'IIDC Dewanpassa',
                'land_rent' => '5000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '500000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '2.00',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '200.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '27.070',
                'available_land_unit' => 'Acre',
                'available_shed' => '0.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'IIDC Lalchhari',
                'land_rent' => '5000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '500000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '2.00',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '200.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '48.610',
                'available_land_unit' => 'Acre',
                'available_shed' => '0.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'IIDC Sarasima',
                'land_rent' => '5000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '500000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '2.00',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '200.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '0.050',
                'available_land_unit' => 'Acre',
                'available_shed' => '0.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Kumarghat Industrial Estate',
                'land_rent' => '6500.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '650000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '2.80',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '13.250',
                'available_land_unit' => 'Acre',
                'available_shed' => '4131.840',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Low Cost Shed at R.K Nagar',
                'land_rent' => '10000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '1000000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '3.20',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '0.200',
                'available_land_unit' => 'Acre',
                'available_shed' => '28000.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Low Cost Sheds at Bodhjungnagar',
                'land_rent' => '0.00',
                'land_rent_unit' => 'Sq. Ft',
                'land_premium' => '0.00',
                'land_premium_unit' => 'Sq. Ft',
                'shed_rent' => '3.20',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '0.000',
                'available_land_unit' => 'Sq. Ft',
                'available_shed' => '5000.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Nagichhera Industrial Area',
                'land_rent' => '10000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '1000000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '4.00',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '400.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '0.000',
                'available_land_unit' => 'Acre',
                'available_shed' => '0.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'no',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'R.K. Nagar Industrial Area',
                'land_rent' => '10000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '1000000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '3.20',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '280.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '7.300',
                'available_land_unit' => 'Acre',
                'available_shed' => '3870.200',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Shantirbazaar Industrial Area',
                'land_rent' => '6000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '500000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '2.00',
                'shed_rent_unit' => 'Sq. Ft',
                'shed_premium' => '200.00',
                'shed_premium_unit' => 'Sq. Ft',
                'available_land' => '8.200',
                'available_land_unit' => 'Acre',
                'available_shed' => '0.000',
                'available_shed_unit' => 'Sq. Ft',
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'industrial_estate_name' => 'Tulakona Industrial Area',
                'land_rent' => '5000.00',
                'land_rent_unit' => 'Acre',
                'land_premium' => '500000.00',
                'land_premium_unit' => 'Acre',
                'shed_rent' => '0.00',
                'shed_rent_unit' => 'Acre',
                'shed_premium' => '0.00',
                'shed_premium_unit' => 'Acre',
                'available_land' => null,
                'available_land_unit' => null,
                'available_shed' => null,
                'available_shed_unit' => null,
                'availability' => 'yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    public function down(): void
    {
        Schema::dropIfExists('industrial_estates');
    }
};
